[[redirects]]
    from = "/"
    to = "/il"
    status = 302
    force = true
    conditions = {Language = ["he"]}

[[redirects]]
    from = "/"
    to = "/il"
    status = 302
    force = true
    conditions = {Country = "il"}