[[redirects]]
    from = "/"
    to = "/il?d=:d"
    status = 302
    force = true
    query = {d = ":d"}
    conditions = {Language = ["he"]}

[[redirects]]
    from = "/"
    to = "/il?d=:d"
    status = 302
    force = true
    query = {d = ":d"}
    conditions = {Country = ["il"]}

[[redirects]]
    from = "/"
    to = "/il?fbclid=:fbclid"
    status = 302
    force = true
    query = {fbclid = ":fbclid"}
    conditions = {Language = ["he"]}

[[redirects]]
    from = "/"
    to = "/il?fbclid=:fbclid"
    status = 302
    force = true
    query = {fbclid = ":fbclid"}
    conditions = {Country = ["il"]}

[[redirects]]
    from = "/"
    to = "/il"
    status = 302
    force = true
    conditions = {Language = ["he"]}

[[redirects]]
    from = "/"
    to = "/il"
    status = 302
    force = true
    conditions = {Country = ["il"]}